name: MetnaVadq
description: "Beta app for course work 2023/2024"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  http: ^1.1.2
  flutter_secure_storage: ^9.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/utils/images/